
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompanyeans.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 12;
  public static final int SEMI_COLON = 5;
  public static final int PROGRAMA = 11;
  public static final int COLON = 4;
  public static final int EQUAL = 14;
  public static final int EOF = 0;
  public static final int NUMERO = 8;
  public static final int CLOSE_PARENTHESIS = 3;
  public static final int error = 1;
  public static final int PROCEDIMIENTO = 6;
  public static final int SIMBOLO = 9;
  public static final int END = 10;
  public static final int BEGIN = 7;
  public static final int PARAM = 13;
  public static final int OPEN_PARENTHESIS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "COLON",
  "SEMI_COLON",
  "PROCEDIMIENTO",
  "BEGIN",
  "NUMERO",
  "SIMBOLO",
  "END",
  "PROGRAMA",
  "INTEGER",
  "PARAM",
  "EQUAL"
  };
}

